// generated 2008/3/7 8:21:06 CET by abegeman@sonyx.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/abegeman/projects/c_projekt/gcnccam/gcnccam.glade
// for gtk 2.8.20 and gtkmm 2.8.8
//
// Please modify the corresponding derived classes in ./src/DialogSetting.hh and./src/DialogSetting.cc

#ifndef _DIALOGSETTING_GLADE_HH
#  define _DIALOGSETTING_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/dialog.h>
#include <gtkmm/tooltips.h>
#include <gtkmm/button.h>
#include <gtkmm/buttonbox.h>
#include <gtkmm/label.h>
#include <gtkmm/combobox.h>
#include <gtkmm/box.h>
#include <gtkmm/checkbutton.h>
#include <gtkmm/entry.h>
#include <gtkmm/notebook.h>

class DialogSetting_glade : public Gtk::Dialog
{  
        
        GlademmData *gmm_data;
public:
        Gtk::Tooltips _tooltips;
        class Gtk::Dialog * DialogSetting;
        class Gtk::Button * cancelbutton1;
        class Gtk::Button * okbutton1;
        class Gtk::Label * label42;
        class Gtk::ComboBox * combo_units;
        class Gtk::HBox * hbox25;
        class Gtk::Label * label43;
        class Gtk::Label * label_unit_length;
        class Gtk::HBox * hbox26;
        class Gtk::Label * label45;
        class Gtk::Label * label_unit_speed;
        class Gtk::HBox * hbox27;
        class Gtk::VBox * vbox10;
        class Gtk::Label * label41;
        class Gtk::Label * label60;
        class Gtk::CheckButton * check_tool_change;
        class Gtk::HBox * hbox36;
        class Gtk::Label * label55;
        class Gtk::Label * label56;
        class Gtk::Entry * entry_tool_change_x;
        class Gtk::Label * label57;
        class Gtk::Entry * entry_tool_change_y;
        class Gtk::Label * label58;
        class Gtk::Entry * entry_tool_change_z;
        class Gtk::Label * label_tool_change_pos_unit;
        class Gtk::HBox * hbox34;
        class Gtk::Label * label51;
        class Gtk::CheckButton * check_tool_sensor;
        class Gtk::HBox * hbox29;
        class Gtk::Label * label47;
        class Gtk::Label * label48;
        class Gtk::Entry * entry_tool_sensor_x;
        class Gtk::Label * label49;
        class Gtk::Entry * entry_tool_sensor_y;
        class Gtk::Label * label50;
        class Gtk::Entry * entry_tool_sensor_z;
        class Gtk::Label * label_tool_sensor_pos_unit;
        class Gtk::HBox * hbox28;
        class Gtk::Label * label54;
        class Gtk::Entry * entry_tool_sensor_height;
        class Gtk::Label * label_tool_sensor_height_unit;
        class Gtk::HBox * hbox33;
        class Gtk::Label * label52;
        class Gtk::Entry * entry_touchoff_zpos;
        class Gtk::Label * label_touchoff_unit;
        class Gtk::HBox * hbox30;
        class Gtk::Label * label53;
        class Gtk::Entry * entry_probe_feed_rate;
        class Gtk::HBox * hbox32;
        class Gtk::Label * label_probe_feed_rate_unit;
        class Gtk::HBox * hbox31;
        class Gtk::VBox * vbox8;
        class Gtk::Label * label34;
        class Gtk::Label * label61;
        class Gtk::CheckButton * check_add_exit_pos;
        class Gtk::HBox * hbox37;
        class Gtk::Label * label62;
        class Gtk::Label * label63;
        class Gtk::Entry * entry_exit_pos_x;
        class Gtk::Label * label64;
        class Gtk::Entry * entry_exit_pos_y;
        class Gtk::Label * label65;
        class Gtk::Entry * entry_exit_pos_z;
        class Gtk::Label * label_exit_pos_unit;
        class Gtk::HBox * hbox38;
        class Gtk::VBox * vbox9;
        class Gtk::Label * label35;
        class Gtk::Notebook * notebook2;
protected:
        
        DialogSetting_glade();
        
        ~DialogSetting_glade();
private:
        virtual void on_combo_units_changed() = 0;
        virtual void on_check_tool_change_toggled() = 0;
        virtual void on_check_tool_sensor_toggled() = 0;
        virtual void on_check_add_exit_pos_toggled() = 0;
};
#endif
