// generated 2008/4/27 18:05:52 CEST by abegeman@sonyx.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/abegeman/sf_project/gcnccam/trunk/gcnccam.glade
// for gtk 2.8.20 and gtkmm 2.8.8
//
// Please modify the corresponding derived classes in ./src/FrameTool.hh and./src/FrameTool.cc

#ifndef _FRAMETOOL_GLADE_HH
#  define _FRAMETOOL_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/frame.h>
#include <gtkmm/label.h>
#include <gtkmm/entry.h>
#include <gtkmm/box.h>
#include <gtkmm/button.h>

class FrameTool_glade : public Gtk::Frame
{  
public:
        
        class Gtk::Frame * FrameTool;
        class Gtk::Label * label11;
        class Gtk::Entry * entry_tool_number;
        class Gtk::HBox * hbox1;
        class Gtk::Label * label14;
        class Gtk::Entry * entry_tool_len;
        class Gtk::Label * label_tool_len_unit;
        class Gtk::HBox * hbox2;
        class Gtk::Label * label12;
        class Gtk::Entry * entry_tool_dia;
        class Gtk::Label * label_tool_dia_unit;
        class Gtk::HBox * hbox3;
        class Gtk::Label * label13;
        class Gtk::Entry * entry_tool_comment;
        class Gtk::HBox * hbox4;
        class Gtk::VBox * vbox3;
        class Gtk::Button * button_ok;
        class Gtk::Button * button_cancel;
        class Gtk::VBox * vbox5;
        class Gtk::HBox * hbox17;
protected:
        
        FrameTool_glade(GlademmData *gmm_data);
        
        ~FrameTool_glade();
private:
        virtual void on_entry_tool_number_changed() = 0;
        virtual void on_button_ok_clicked() = 0;
        virtual void on_button_cancel_clicked() = 0;
};
#endif
