// generated 2007/9/9 16:37:55 CEST by abegeman@sonyx.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/abegeman/projects/c_projekt/gxcam/gxcam.glade
// for gtk 2.10.13 and gtkmm 2.10.10
//
// Please modify the corresponding derived classes in ./src/WindowLayerPropertyFrame.cc


#if defined __GNUC__ && __GNUC__ < 3
#error This program will crash if compiled with g++ 2.x
// see the dynamic_cast bug in the gtkmm FAQ
#endif //
#include "config.h"
/*
 * Standard gettext macros.
 */
#ifdef ENABLE_NLS
#  include <libintl.h>
#  undef _
#  define _(String) dgettext (GETTEXT_PACKAGE, String)
#  ifdef gettext_noop
#    define N_(String) gettext_noop (String)
#  else
#    define N_(String) (String)
#  endif
#else
#  define textdomain(String) (String)
#  define gettext(String) (String)
#  define dgettext(Domain,Message) (Message)
#  define dcgettext(Domain,Message,Type) (Message)
#  define bindtextdomain(Domain,Directory) (Domain)
#  define _(String) (String)
#  define N_(String) (String)
#endif
#include <gtkmmconfig.h>
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
#include <sigc++/compatibility.h>
#define GMM_GTKMM_22_24(a,b) b
#else //gtkmm 2.2
#define GMM_GTKMM_22_24(a,b) a
#endif //
#include "WindowLayerPropertyFrame_glade.hh"
#include <gdk/gdkkeysyms.h>
#include <gtkmm/accelgroup.h>
#include "FrameLayerProperty.hh"

WindowLayerPropertyFrame_glade::WindowLayerPropertyFrame_glade(
) : Gtk::Window(Gtk::WINDOW_TOPLEVEL)
{  WindowLayerPropertyFrame = this;
   gmm_data = new GlademmData(get_accel_group());
   FrameLayerProperty = Gtk::manage(new class FrameLayerProperty(gmm_data));
   WindowLayerPropertyFrame->set_title(_("window1"));
   WindowLayerPropertyFrame->set_modal(false);
   WindowLayerPropertyFrame->property_window_position().set_value(Gtk::WIN_POS_NONE);
   WindowLayerPropertyFrame->set_resizable(true);
   WindowLayerPropertyFrame->property_destroy_with_parent().set_value(false);
   WindowLayerPropertyFrame->add(*FrameLayerProperty);
   WindowLayerPropertyFrame->show();
}

WindowLayerPropertyFrame_glade::~WindowLayerPropertyFrame_glade()
{  delete gmm_data;
}
